name: Deploy to GitHub pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install & Build 🔧
        run: |
          npm install --location=global pnpm
          pnpm run cd

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: gh-pages
          folder: .svelte-kit/output
